// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_newsapi/test/features/news/domain/usecase/news_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_newsapi/core/models/api_result_model.dart' as _i3;
import 'package:flutter_newsapi/features/news/data/datasources/news_data_source.dart'
    as _i2;
import 'package:flutter_newsapi/features/news/data/repositories/news_repository_impl.dart'
    as _i4;
import 'package:flutter_newsapi/features/news/domain/entities/news_list_entity.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNewsDataSource_0 extends _i1.SmartFake
    implements _i2.NewsDataSource {
  _FakeNewsDataSource_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiResultModel_1<T> extends _i1.SmartFake
    implements _i3.ApiResultModel<T> {
  _FakeApiResultModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NewsRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewsRepositoryImpl extends _i1.Mock
    implements _i4.NewsRepositoryImpl {
  MockNewsRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NewsDataSource get remoteDataSource => (super.noSuchMethod(
        Invocation.getter(#remoteDataSource),
        returnValue: _FakeNewsDataSource_0(
          this,
          Invocation.getter(#remoteDataSource),
        ),
      ) as _i2.NewsDataSource);

  @override
  _i5.Future<_i3.ApiResultModel<_i6.NewsListEntity>> getNewsList({
    required String? query,
    required int? page,
    int? itemPerPage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNewsList,
          [],
          {
            #query: query,
            #page: page,
            #itemPerPage: itemPerPage,
          },
        ),
        returnValue: _i5.Future<_i3.ApiResultModel<_i6.NewsListEntity>>.value(
            _FakeApiResultModel_1<_i6.NewsListEntity>(
          this,
          Invocation.method(
            #getNewsList,
            [],
            {
              #query: query,
              #page: page,
              #itemPerPage: itemPerPage,
            },
          ),
        )),
      ) as _i5.Future<_i3.ApiResultModel<_i6.NewsListEntity>>);
}
