// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_newsapi/test/features/news/data/datasources/news_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dio/dio.dart' as _i2;
import 'package:flutter_newsapi/core/dio/base_dio.dart' as _i4;
import 'package:flutter_newsapi/core/models/api_result_model.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiResultModel_1<T> extends _i1.SmartFake
    implements _i3.ApiResultModel<T> {
  _FakeApiResultModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BaseDio].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseDio extends _i1.Mock implements _i4.BaseDio {
  MockBaseDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  _i6.Future<_i3.ApiResultModel<_i2.Response<dynamic>>> get({
    required String? url,
    Map<String, dynamic>? param,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [],
          {
            #url: url,
            #param: param,
          },
        ),
        returnValue:
            _i6.Future<_i3.ApiResultModel<_i2.Response<dynamic>>>.value(
                _FakeApiResultModel_1<_i2.Response<dynamic>>(
          this,
          Invocation.method(
            #get,
            [],
            {
              #url: url,
              #param: param,
            },
          ),
        )),
      ) as _i6.Future<_i3.ApiResultModel<_i2.Response<dynamic>>>);
}
